CREATE TABLE IMMEUBLE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOM VARCHAR(255) NOT NULL,
    ADRESSE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    EQUIPEMENTS VARCHAR(255)
);

CREATE TABLE UNITELOCATION (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO_UNITE VARCHAR(255) NOT NULL,
    NOMBRE_PIECES INT,
    SUPERFICIE DECIMAL(10, 2),
    LOYER DECIMAL(10, 2),
    IMMEUBLE_ID INT,
    FOREIGN KEY (IMMEUBLE_ID) REFERENCES IMMEUBLE(ID)
);

CREATE TABLE LOCATAIRE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOM VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    MOT_DE_PASSE VARCHAR(255) NOT NULL
);

CREATE TABLE CONTRATLOCATION (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATE_DEBUT DATE NOT NULL,
    DATE_FIN DATE NOT NULL,
    UNITE_LOCATION_ID INT,
    LOCATAIRE_ID INT,
    FOREIGN KEY (UNITE_LOCATION_ID) REFERENCES UNITELOCATION(ID),
    FOREIGN KEY (LOCATAIRE_ID) REFERENCES LOCATAIRE(ID)
);

CREATE TABLE PAIEMENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MONTANT DECIMAL(10, 2) NOT NULL,
    DATE_PAIEMENT DATE NOT NULL,
    CONTRAT_LOCATION_ID INT,
    FOREIGN KEY (CONTRAT_LOCATION_ID) REFERENCES CONTRATLOCATION(ID)
);

CREATE TABLE UTILISATEUR (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOM_UTILISATEUR VARCHAR(255) UNIQUE NOT NULL,
    MOT_DE_PASSE VARCHAR(255) NOT NULL,
    ROLE ENUM('ADMIN', 'PROPRIETAIRE', 'LOCATAIRE') NOT NULL
);

-- ajout des colonnes images
ALTER TABLE IMMEUBLE ADD (IMAGE VARCHAR(255));

ALTER TABLE UNITELOCATION ADD (IMAGE VARCHAR(255));

ALTER TABLE UNITELOCATION ADD (TARIF_LOCATION DECIMAL(10, 2));